### PR TITLE
Add RabbitVCS support

### PR DESCRIPTION
**Pull request by EmiyaSyahriel**
I've implemented the support for issue #7 that I've opened. I've tested only functionalities that I usually use e.g Commit, Update, Repo-browser and they are working as I expected, And the rest of function should also working fine too. Theree is still some leftover from the TortoiseSVN's.

However, I'm worrying that RabbitVCS executes these commands in context of other VCS program in case of the project uses multiple VCS at once, this because RabbitVCS auto-detects if the project is using SVN, Git and Hg. But since this plugin disables it's SVN integration when it doesn't detect one, it should be fine, right?

And also, why is there still this line in `CLIContextMenus.cs`?
```csharp
#ifdef UNITY_EDITOR_WIN
```
Shouldn't CLI good for all platform? The changes I made is adapting the current code by adding `|| UNITY_EDITOR_LINUX`, though.

### CODE REVIEW

**Comment by NibbleByte** [comment]
> And also, why is there still this line in CLIContextMenus.cs?
> #ifdef UNITY_EDITOR_WIN

Because of late night copy-paste. :D It needs to be removed.

Your code looks fine. I have one important question - notice the fields at the top:
```c#
protected override string FileArgumentsSeparator => "*";
protected override bool FileArgumentsSurroundQuotes => false;
``` 

They specify how to pass multiple files as argument. TortoiseSVN wants to concatenate them with '*' which is not very common. Example:
> TortoiseProc.exe /command:commit /path:"Assets\file1.txt*Assets\file2.txt"

Can you confirm that "rabbitvcs" has this syntax with multiple files? Try to select multiple assets in Unity and select "commit", see if it works. I highly doubt they want '*' symbol - probably empty space is the right one. SnailSVN on OSX uses space. 
If rabbitvcs doesn't support multiple files, a different approach is needed.

If I'm right, you probably want empty space and surround quotes = true. This also means that the commands below need to be without quotes. Example:
`var result = ShellUtils.ExecuteCommand(ClientCommand, $"changes \"{pathsArg}\"", wait);`
becomes this:
`var result = ShellUtils.ExecuteCommand(ClientCommand, $"changes {pathsArg}", wait);`

Sadly, I can't test this easily, so it's up to you.

**Comment by EmiyaSyahriel** [comment]
You're right, the command syntax should be like : 
```shell
rabbitvcs commit "file1" ["file2"] ...
```
I'll fix it so that it didn't make any problem in the future and other machines too. Since after some extensive testing, it did nothing when executing the commands with multiple file (I usually call commit and other command with the entire folder as context and deselects files I'm not committing, probably that's way I'm missed these problems).

**Comment by EmiyaSyahriel** [comment]
I've committed the fix, please re-review them.

**Comment by NibbleByte** [comment]
It looks good. :)
I'll merge the request next week, so you have more time to tweak it if you find any more issues.

**Pull request merged**
